apiVersion: v1
kind: Service
metadata:
  name: guestbookservice-service
spec:
  selector:
    app: "guestbookservice-app"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP