apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: guestbookdb
spec:
  selector:
    matchLabels:
      app: guestbookdb
  replicas: 1
  serviceName: guestbookdb-service
  template:
    metadata:
      labels:
        app: guestbookdb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: guestbookdb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: guestbookdb-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi